apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-task-db
data:
  SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://task:tasktask@knee-pg-postgresql-0.knee-pg-postgresql-hl.vrnctf.svc.cluster.local/task_db