# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать 

# Обязательные поля
# Имя задачи на CTFd
name: Hello world
# Никнейм в Telegram
author: "@kotz1k"
# Описание таска на платформе.
description: | 
  wow it's flag - vrnctf{hellow_world}

  <img src="//3.downloader.disk.yandex.ru/preview/453fa9b3662ff599e6c4e723a81f39888ab1ffd56abecd21c05606e126ad8853/inf/NePWj0wabjYrvLIlmfeGCoB1TqLtAevRPf2tJOV5cgtYkVtbNsJIfhie1xdUopoR_OH0K0-l25yRtLW1alK8XQ%3D%3D?uid=574402728&filename=image_2023-03-24_13-30-35%20%282%29.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=574402728&tknv=v2&size=2560x694" style="max-width:100%; height:auto;">
# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: joy
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  # Флаг можно задать так
  - vrnctf{hellow_world}

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/task.zip

# Подсказки. Можно передавать словари и строки
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
